terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }

  required_version = ">= 1.2.0"
}

provider "aws" {
  profile = "default"
  region  = "ap-northeast-2"
}

variable "generated_key_name" {
  type        = string
  default     = "pk-key"
  description = "Key-pair generated by Terraform"
}

resource "aws_instance" "dev_app_server" {
  ami                    = "ami-0ea5eb4b05645aa8a"
  instance_type          = "t2.micro"
  key_name               = aws_key_pair.pk_key_pair.key_name
  vpc_security_group_ids = [aws_security_group.dev_security_group.id]

  tags = {
    Name = "DevAppServer"
  }
}

resource "aws_instance" "dev_nginx_server" {
  ami                    = "ami-0ea5eb4b05645aa8a"
  instance_type          = "t2.micro"
  key_name               = aws_key_pair.pk_key_pair.key_name
  vpc_security_group_ids = [aws_security_group.dev_security_group.id]

  tags = {
    Name = "DevNginxServer"
  }
}

resource "aws_security_group" "dev_security_group" {
  egress = [
    {
      cidr_blocks      = ["0.0.0.0/0", ]
      description      = ""
      from_port        = 0
      ipv6_cidr_blocks = []
      prefix_list_ids  = []
      protocol         = "-1"
      security_groups  = []
      self             = false
      to_port          = 0
    }
  ]

  ingress = [
    {
      cidr_blocks      = ["0.0.0.0/0", ]
      description      = ""
      from_port        = 22
      ipv6_cidr_blocks = []
      prefix_list_ids  = []
      protocol         = "tcp"
      security_groups  = []
      self             = false
      to_port          = 22
    }
  ]
}

resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "pk_key_pair" {
  key_name   = "pk-key"
  public_key = tls_private_key.ssh.public_key_openssh

  provisioner "local-exec" {
    command = <<-EOT
      echo '${tls_private_key.ssh.private_key_pem}' > ./'${var.generated_key_name}'.pem
      chmod 400 ./'${var.generated_key_name}'.pem
    EOT
  }
}
